### ISSUE TITLE
more boms for testing

### ISSUE THREAD

**Issue by jayvdb** [timrburnham/bom_open#13]
https://github.com/jeff00seattle/pyfortified-requests/blob/master/pyfortified_requests/support/bom_encoding.py has a nice list of boms and the encoding name, which could be used to create more test data files and ensure they also work.

**Comment by jayvdb** [comment]
The cp* boms there are being detected as utf-8 , but the bom comes out and is scrambled, like `ď»żhello`

More good ones at https://en.wikipedia.org/wiki/Byte_order_mark#Byte_order_marks_by_encoding

**Comment by jayvdb** [comment]
> More good ones at https://en.wikipedia.org/wiki/Byte_order_mark#Byte_order_marks_by_encoding

All of those (except utf6/16/32) also detect as either ascii, iso-8859-1, windows-1252

The detection algorithm needs to be improved, as chardet doesnt seem to be working very well.

**Comment by jayvdb** [comment]
https://github.com/PyYoshi/cChardet looks good.

**Comment by jayvdb** [comment]
> PyYoshi/cChardet looks good.

Not so good, as https://github.com/PyYoshi/cChardet/issues/26 is a regression when compared to `chardet`, and curly quotes is an unfortunately really common problem.

Other boms not detected: https://github.com/PyYoshi/uchardet/issues/4

We cant use the highest confidence of the two either, as cchardet has a higher confidence for curlies, but it is wrong.

curlies:

- chardet: `{'encoding': 'Windows-1252', 'confidence': 0.73, 'language': ''}`
- cchardet: `{'encoding': 'MacCentralEurope', 'confidence': 0.8183978796005249}`

gb-18030:

- chardet: `{'encoding': 'Windows-1252', 'confidence': 0.73, 'language': ''}`
- cchardet: `{'encoding': 'GB18030', 'confidence': 0.9900000095367432}`

We might be able to use a rule like "if cchardet confidence is >90% then use its choice, otherwise use chardet."

**Comment by jayvdb** [comment]
Also created https://github.com/Joungkyun/python-chardet/issues/3 and https://github.com/thombashi/mbstrdecoder/issues/2 , because those two have good results, but all have one or more problems.

**Comment by timrburnham** [comment]
> The cp* boms there are being detected as utf-8 , but the bom comes out and is scrambled, like `ď»żhello`

I would expect this. Non-Unicode encodings, such as Windows-1252, don't have BOMs. CP1252 characters represented within (let's say) UTF-8 don't affect the BOM that started the file. And multiple international code pages can be represented within the same Unicode file. Do you understand what jeff00seattle is trying to represent with those 6-byte sequences?

**Comment by jayvdb** [comment]
Not sure. The python codecs dont encode the unicode BOM as that
```py
>>> '\ufeff'.encode('cp1250')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib64/python3.7/encodings/cp1250.py", line 12, in encode
    return codecs.charmap_encode(input,errors,encoding_table)
UnicodeEncodeError: 'charmap' codec can't encode character '\ufeff' in position 0: character maps to <undefined>
```

I thought maybe they are some 'magic' heuristic, but unix command `file` sees those bytes as `UTF-8 Unicode text`

That part of the code comes from the initial commit, https://github.com/jeff00seattle/pyfortified-requests/commit/3894b2d7bca6c941ddf3489393d7c8f4c13cba22 , so the commit history doesnt tell us much.

He also committed the same at https://github.com/hasdank/facebook-ads-worker/commit/401da897dc47505df5150e3b55db3a6d08a96f9f#diff-89cb7719c9b5c9342ab6e6ba745c75b3

And 12 hours ago at https://github.com/jeff00seattle/facebook-api-scripts/blob/076b8ee7b09dc912f0adb2f20faa5c0ca007eab0/scripts/py_sources/utils.py

ping @jeff00seattle , maybe you can enlighten us where you encountered those.

**Comment by jayvdb** [comment]
Cant make much sense out of these either
```py
>>> b'\xc4\x8f\xc2\xbb\xc5\xbc'.decode('cp1250')
'ÄŹÂ»ĹĽ'
>>> b'\xd0\xbf\xc2\xbb\xd1\x97'.decode('cp1251')
'РїВ»С—'
>>> b'\xc3\xaf\xc2\xbb\xc2\xbf'.decode('cp1252')
'Ã¯Â»Â¿'
>>> b'\xce\xbf\xc2\xbb\xce\x8f'.decode('cp1253')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib64/python3.7/encodings/cp1253.py", line 15, in decode
    return codecs.charmap_decode(input,errors,decoding_table)
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8f in position 5: character maps to <undefined>
>>> b'\xc3\xaf\xc2\xbb\xc2\xbf'.decode('cp1254')
'Ã¯Â»Â¿'
>>> b'\xd7\x9f\xc2\xbb\xc2\xbf'.decode('cp1255')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib64/python3.7/encodings/cp1255.py", line 15, in decode
    return codecs.charmap_decode(input,errors,decoding_table)
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9f in position 1: character maps to <undefined>
>>> b'\xc3\xaf\xc2\xbb\xd8\x9f'.decode('cp1256')
'أ¯آ»طں'
>>> b'\xc4\xbc\xc2\xbb\xc3\xa6'.decode('cp1257')
'Ä¼Ā»Ć¦'
>>> b'\xc3\xaf\xc2\xbb\xc2\xbf'.decode('cp1258')
'Ă¯Â»Â¿'
```
